### ISSUE TITLE
Task Preloading

### ISSUE THREAD

**Issue by ferronrsmith** [bangsh/bangsh#7]
Preloading of task clobber the global scope.

I have two separate files with _run defined in both. Which task i call the _run from the first task loaded always gets executed. Not a bug, but a short coming.

**Comment by bellthoven** [comment]
My main idea is to pack all the files into a single file which can be deployed or executed without the need of bang.sh being installed.

So, I think prefixing function names may be a good idea to avoid this kind of things. What do you think about it? Is prefixing a good idea?

I mean, instead of just declaring `_run` for both functions, maybe we could have `_<task_name>.run` or `<task_name>._run`, what do you think?

**Comment by ferronrsmith** [comment]
That's actually a great idea. That would be awesome to have 1 file to do everything.

**Comment by bellthoven** [comment]
:tada: nice to hear the feedback!

P.S. I am closing this issue then. Feel free to keep the conversation or open any other issue with your concerns.
